version: '3.8'

services:
  frpc:
    image: snowdreamtech/frpc:latest
    volumes:
      - ./frpc.toml:/etc/frp/frpc.toml
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    env_file:
      - secrets/vaultwarden/.env
    ports:
      - "${VAULTWARDEN_PORT_HTTP:-8080}:80"
      - "${VAULTWARDEN_PORT_WEBSOCKET:-3012}:3012"
    volumes:
      - vaultwarden_data:/data
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
volumes:
  caddy_data:
  vaultwarden_data:

